const IQuestionsContext = {
    impacto: 0,
    beneficio: 0,
    reversivel: 0,
    reversivelCusto: 0,
    necessario: 0,
    emocao: 0,
    velocidade: 0,
    fatos: 0,
    experiencia: 0,
    desejo: 0,
    pressao: 0,
    trauma: 0,
    opiniao: 0,
    ignorarFatos: 0,
    plano: 0,
    proposito: 0,
    razao: 0,
    confortavel: 0,
    coletivo: 0,
    deus: 0,
    espiritual: 0,  
}

export { IQuestionsContext };